### PR TITLE
add use save and exact by default

### PR DESCRIPTION
**Pull request by anotheredward**
Sick of forgetting to type --save at the end of every npm install, not sure if we use patch versions of libraries? Fear no more, company-wide default npm config settings are here!

### CODE REVIEW

**Comment by ebuckley** [comment]
I like `npm config set save=true` this seems to be a pure timesaver.

**Comment by ebuckley** [comment]
Having `save-exact` set can mean that we do not get security updates, at the start of a project it can be very useful to have updates to libraries throughout the life of the project. That said, we can always use a service to check when packages become outdated.

**Comment by anotheredward** [comment]
I have used `npm-check-updates` and `nsp` in the past during Security review for this reason

**Comment by markstuart** [comment]
Yeah, I have become increasingly more afraid of automatic package version updates... we are working in an ecosystem where not every package maintainer appears to manage semver principles very well, and even patch level updates can break APIs at times in my experience. I'd be happy enough to lock versions down, although it probably should become a part of our culture that we do run an update tool regularly to pull in security fixes at least.

One thing to note is that this only protects us at the top level. The fixed versions of our dependencies have non-fixed versions in their dependencies and so on and so on. This is the shifting sands of the ecosystem we work within. 😨 

Regards the `--save`, seems like a minor win, but I like it.

**Comment by anotheredward** [comment]
Will merge once we discuss pinning at the next tech stack meeting

**Comment by digitalsadhu** [comment]
> One thing to note is that this only protects us at the top level. The fixed versions of our dependencies have non-fixed versions in their dependencies and so on and so on. This is the shifting sands of the ecosystem we work within. 😨

This is what shrinkwrap should solve for us no? Would not the bigger win be to use shrinkwrap rather than locking down exact versions?

**Comment by ebuckley** [comment]
Is this solved by Yarn :allthethings: ?

**Comment by anotheredward** [comment]
No, we have lots of legacy projects and not all of them use Yarn

**Comment by anotheredward** [comment]
That said, the latest versions of NPM now have a lockfile, so 🤷‍♂️ , think we'll just close this one and move on.

**Pull request closed without merging**
